### ISSUE TITLE
Client: Tile can get stuck on board when playing

### ISSUE THREAD

**Issue by richardjamesw** [CSC480-18S/Blue-Team#196] opened 2018-04-20 18:26 UTC
Steps:
Place tile on board
Wait for hand to reset
Try moving tile

Workaround: Refresh webpage

**Comment by tealyn** [comment] 2018-05-07 21:50
unable to reproduce

**Comment by BrendanOswego** [comment] 2018-05-09 17:47
since this was not able to be reproduced I will close this issue.

**Closed by BrendanOswego** 2018-05-09 17:47 UTC
Labels: bug, ready for qa
